// ============================================================
// CẤU HÌNH WEBSITE - Chỉnh sửa thông tin tại đây
// ============================================================

export const siteInfo = {
  name: 'Long Quảng Cáo & Nội Thất',
  slogan: 'Chất lượng cao - Giá thành hợp lý - Sự lựa chọn tin cậy cho mọi công trình',
  address: '[Địa chỉ công ty]',
  email: '[email@example.com]',
};

// Thông tin liên hệ theo từng Tab/Trang
// Thay đổi số điện thoại và link mạng xã hội tại đây
export const contactByPage = {
  default: {
    phone: '0901 234 567',
    phoneDisplay: '0901.234.567',
    zaloLink: 'https://zalo.me/0901234567',
    facebookLink: 'https://facebook.com/longquangcaonongthat',
    zaloId: '0901234567',
  },
  'bien-quang-cao': {
    phone: '0901 234 567',
    phoneDisplay: '0901.234.567',
    zaloLink: 'https://zalo.me/0901234567',
    facebookLink: 'https://facebook.com/longquangcaonongthat',
    zaloId: '0901234567',
  },
  'noi-that': {
    phone: '0912 345 678',
    phoneDisplay: '0912.345.678',
    zaloLink: 'https://zalo.me/0912345678',
    facebookLink: 'https://facebook.com/longnoithat',
    zaloId: '0912345678',
  },
  'du-an': {
    phone: '0901 234 567',
    phoneDisplay: '0901.234.567',
    zaloLink: 'https://zalo.me/0901234567',
    facebookLink: 'https://facebook.com/longquangcaonongthat',
    zaloId: '0901234567',
  },
  'lien-he': {
    phone: '0901 234 567',
    phoneDisplay: '0901.234.567',
    zaloLink: 'https://zalo.me/0901234567',
    facebookLink: 'https://facebook.com/longquangcaonongthat',
    zaloId: '0901234567',
  },
};

// Sản phẩm Biển Quảng Cáo
export const signageProducts = [
  {
    id: 1,
    name: 'Biển Hộp Đèn LED Premium',
    category: 'hop-den',
    material: '[Mica, Nhôm định hình]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_lightbox.png',
  },
  {
    id: 2,
    name: 'Biển Hộp Đèn Cao Cấp',
    category: 'hop-den',
    material: '[Mica trong, Nhôm]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_lightbox.png',
  },
  {
    id: 3,
    name: 'Biển Alu Phẳng Tiêu Chuẩn',
    category: 'alu',
    material: '[Tôn Alu 3mm]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_alu.png',
  },
  {
    id: 4,
    name: 'Biển Alu Cao Cấp In UV',
    category: 'alu',
    material: '[Tôn Alu 4mm, In UV]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_alu.png',
  },
  {
    id: 5,
    name: 'Chữ Nổi Mica Đèn LED',
    category: 'chu-noi',
    material: '[Mica 5mm, Đèn LED]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_raised.png',
  },
  {
    id: 6,
    name: 'Chữ Nổi Inox Vàng Bóng',
    category: 'chu-noi',
    material: '[Inox 304, Mạ vàng]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_raised.png',
  },
  {
    id: 7,
    name: 'Biển Bảng Quảng Cáo Decal',
    category: 'khac',
    material: '[Decal cán nhiệt]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_alu.png',
  },
  {
    id: 8,
    name: 'Biển Standee Quảng Cáo',
    category: 'khac',
    material: '[Nhôm, In hiflex]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_lightbox.png',
  },
];

// Sản phẩm Nội Thất
export const furnitureProducts = [
  {
    id: 1,
    name: 'Tủ Quần Áo Gỗ Công Nghiệp',
    category: 'tu',
    material: '[MDF phủ Melamine]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_cabinet.png',
  },
  {
    id: 2,
    name: 'Tủ Bếp Cao Cấp',
    category: 'tu',
    material: '[Gỗ Sồi Tự Nhiên]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_cabinet.png',
  },
  {
    id: 3,
    name: 'Kệ Sách Treo Tường',
    category: 'ke',
    material: '[Gỗ thông, Sắt]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_shelf.png',
  },
  {
    id: 4,
    name: 'Kệ Tivi Phòng Khách',
    category: 'ke',
    material: '[MDF phủ veneer sồi]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_shelf.png',
  },
  {
    id: 5,
    name: 'Tủ Đầu Giường Hiện Đại',
    category: 'tu',
    material: '[Gỗ công nghiệp cao cấp]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_cabinet.png',
  },
  {
    id: 6,
    name: 'Kệ Trưng Bày Showroom',
    category: 'ke',
    material: '[Sắt sơn tĩnh điện, Gỗ]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_shelf.png',
  },
  {
    id: 7,
    name: 'Tủ Giày Cửa Gương',
    category: 'tu',
    material: '[MDF, Gương cao cấp]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_cabinet.png',
  },
  {
    id: 8,
    name: 'Kệ Bếp Treo Tường',
    category: 'ke',
    material: '[Inox 304, Thép sơn tĩnh điện]',
    size: '[Theo yêu cầu]',
    price: '[Liên hệ để báo giá]',
    description: '[Mô tả chi tiết sản phẩm]',
    image: '/images/product_shelf.png',
  },
];

// Dự án tiêu biểu
export const featuredProjects = [
  {
    id: 1,
    name: 'Dự Án Chuỗi Cửa Hàng ABC',
    category: 'Biển quảng cáo',
    description: '[Mô tả chi tiết dự án]',
    image: '/images/project_showcase1.png',
    year: '2024',
  },
  {
    id: 2,
    name: 'Nội Thất Văn Phòng XYZ',
    category: 'Nội thất',
    description: '[Mô tả chi tiết dự án]',
    image: '/images/hero_furniture.png',
    year: '2024',
  },
  {
    id: 3,
    name: 'Hệ Thống Biển Hiệu Nhà Hàng',
    category: 'Biển quảng cáo',
    description: '[Mô tả chi tiết dự án]',
    image: '/images/hero_signage.png',
    year: '2023',
  },
  {
    id: 4,
    name: 'Showroom Nội Thất Cao Cấp',
    category: 'Nội thất',
    description: '[Mô tả chi tiết dự án]',
    image: '/images/product_cabinet.png',
    year: '2023',
  },
  {
    id: 5,
    name: 'Bộ Chữ Nổi Trung Tâm Thương Mại',
    category: 'Biển quảng cáo',
    description: '[Mô tả chi tiết dự án]',
    image: '/images/product_raised.png',
    year: '2024',
  },
  {
    id: 6,
    name: 'Hệ Thống Kệ Siêu Thị Mini',
    category: 'Nội thất',
    description: '[Mô tả chi tiết dự án]',
    image: '/images/product_shelf.png',
    year: '2023',
  },
  {
    id: 7,
    name: 'Biển Hộp Đèn Phòng Khám',
    category: 'Biển quảng cáo',
    description: '[Mô tả chi tiết dự án]',
    image: '/images/product_lightbox.png',
    year: '2024',
  },
  {
    id: 8,
    name: 'Nội Thất Căn Hộ Luxury',
    category: 'Nội thất',
    description: '[Mô tả chi tiết dự án]',
    image: '/images/hero_furniture.png',
    year: '2024',
  },
];
